// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfWMU8jqRgw67vdv3OpHjgFQfsTNf767w',
    appId: '1:16729344376:web:bf3875c942e5cebc66208d',
    messagingSenderId: '16729344376',
    projectId: 'firstprojectflutter-4a776',
    authDomain: 'firstprojectflutter-4a776.firebaseapp.com',
    storageBucket: 'firstprojectflutter-4a776.appspot.com',
    measurementId: 'G-CZJH2MM40K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqVVsxH40pi-xT-T48riVjr0PNsR4maM',
    appId: '1:16729344376:android:1b48eef3e6a6a1da66208d',
    messagingSenderId: '16729344376',
    projectId: 'firstprojectflutter-4a776',
    storageBucket: 'firstprojectflutter-4a776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT08YhvMztjcPRZFxwB8fq-Xx5W2BCRec',
    appId: '1:16729344376:ios:23a31e598795e26466208d',
    messagingSenderId: '16729344376',
    projectId: 'firstprojectflutter-4a776',
    storageBucket: 'firstprojectflutter-4a776.appspot.com',
    iosBundleId: 'com.example.firbasefutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT08YhvMztjcPRZFxwB8fq-Xx5W2BCRec',
    appId: '1:16729344376:ios:0200410a7a7ece3666208d',
    messagingSenderId: '16729344376',
    projectId: 'firstprojectflutter-4a776',
    storageBucket: 'firstprojectflutter-4a776.appspot.com',
    iosBundleId: 'com.example.firbasefutter.RunnerTests',
  );
}
